### ISSUE TITLE
无法正常运行。

### ISSUE THREAD

**Issue by Toanlele** [oasosao/speaktext#1]
2024/01/21 20:29:54.709144 main.go:101: ERROR 转语音失败, 数据为空。
2024/01/21 20:29:54.709315 main.go:84: ERROR 保存音频失败 !BADKEY="stat SpeakCache/zh-CN-YunXiNeural_cdfbbf2afb279b182f4682da3c6bedae.mp3: no such file or directory"

**Comment by oasosao** [comment]
speaktext -text="你想说的话"

**Comment by oasosao** [comment]
可能是之前的readme.md文件里面的用法写错了，你参照下面的用法试试。

**windows:**  ` speaktext.exe -text="想说的话"  `

**macos 或 linux ** `speaktext -text="想说的话" `

**Comment by Toanlele** [comment]
2024/01/30 00:29:24.126213 main.go:100: ERROR 转语音失败, 数据为空。
2024/01/30 00:29:24.126444 main.go:83: ERROR 保存音频失败 !BADKEY="stat SpeakCache/zh-CN-YunXiNeural_c153be7d478060896cb451750efe16a6.mp3: no such file or directory"
